#!/usr/bin/env bash
##############################################################################
# Copyright © 2018 AT&T Intellectual Property. All rights reserved.          #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License.                   #
#                                                                            #
# You may obtain a copy of the License at                                    #
#       http://www.apache.org/licenses/LICENSE-2.0                           #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT  #
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.           #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
##############################################################################


read -p "Are you sure you wish to continue? (y/n)" REPLY
if [ "$REPLY" != "y" ]; then
   echo "Good Bye"
   exit
fi

set -x

# Check that we are root
if [[ $(whoami) != "root" ]]
then
  echo "Must be root to run $0"
  exit -1
fi

export KUBECONFIG=/etc/kubernetes/admin/kubeconfig.yaml

kubectl drain --delete-local-data --force $(hostname)
systemctl stop kubelet
df -lh | awk '{ print $6 }' | grep -i kubelet | xargs -I {} umount -f -l {}
df -lh | awk '{ print $6 }' | grep -i docker | grep -v "/var/lib" | xargs -I {} umount -f -l {}
umount -f -l /run/user/0
mount -a
docker rm -fv $(docker ps -aq)

#systemctl stop docker
apt-get remove --autoremove --purge -y docker-engine=1.13.1-0~ubuntu-xenial socat=1.7.3.1-1
#Docker
rm -rf /dev/docker-data
rm -rf /var/lib/docker/*
rm -rf /etc/docker
rm -rf /etc/systemd/system/docker.service.d
rm -rf /var/lib/dockershim

#Ceph
rm -rf /var/lib/openstack-helm
rm -rf /var/lib/ceph
dd if=/dev/zero of=/dev/sdb  bs=512  count=1 conv=notrunc
dd if=/dev/zero of=/dev/sdc  bs=512  count=1 conv=notrunc
rm -rf /var/lib/openstack-helm/ceph/journal0/*
rm -rf /var/lib/openstack-helm/ceph/journal1/*

#Kubernetes
rm -rf /etc/kubernetes
rm -rf /usr/local/bin/kubectl
rm -rf /usr/local/bin/kubelet
rm -rf /var/lib/kubelet
rm -rf /etc/systemd/system/kubelet
rm -rf /etc/systemd/system/kubelet.service

# apt-get install creates the following directory
rm -rf /etc/systemd/system/kubelet.service.d/
rm -rf /var/log/pods
rm -rf /var/log/containers

#etcd
rm -rf /var/lib/auxiliary-etcd-0
rm -rf /var/lib/auxiliary-etcd-1
rm -rf /var/lib/auxiliary-calico-etcd-0
rm -rf /var/lib/auxiliary-calico-etcd-1
rm -rf /var/lib/calico-etcd
rm -rf /var/lib/kube-etcd

#nova
rm -rf /var/lib/nova/*

#ONAP
rm -rf /dockerdata-nfs/onap/
rm -rf /etc/dnsmasq.d
rm -rf /opt/cni
rm -rf /usr/local/bin/bootstrap
rm -rf /usr/local/bin/helm
rm -rf /var/lib/prom.done

# Remove files generated by Promenade
rm -rf /etc/cni
rm -rf /etc/coredns
rm -rf /etc/etcd
rm -rf /etc/genesis
rm -rf /var/lib/etcd
rm -rf /var/lib/kubelet/pods
