#!/bin/bash

export GENESIS_HOST=192.168.2.40
echo GENESIS_HOST=$GENESIS_HOST
export PXE_INTERFACE=eno3
echo PXE_INTERFACE=$PXE_INTERFACE
export HOST_INTERFACE=bond0.41
echo HOST_INTERFACE=$HOST_INTERFACE
