#!/bin/bash

export GENESIS_HOST=135.197.242.59
echo GENESIS_HOST=$GENESIS_HOST
export PXE_INTERFACE=eno1
echo PXE_INTERFACE=$PXE_INTERFACE
export HOST_INTERFACE=eno1
echo HOST_INTERFACE=$HOST_INTERFACE
